import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ChangeEvent } from 'react'
import styles from '../styles/Home.module.css'

interface HomeProps {
  data: {
    apikey: string;
    cloudname: string;
    signature: string;
    timestamp: number;
    eager: string;
    folder: string;
  }
}

const Home: NextPage<HomeProps> = ({ data }) => {
  console.log('data', data)
  const url = "https://api.cloudinary.com/v1_1/" + data.cloudname + "/auto/upload"


  const handleUpload = async (e: ChangeEvent<HTMLInputElement>) => {
    try {

      const formData = new FormData();

      const files = e.target.files
      if (files) {

        formData.append('file', files[0])
        formData.append('api_key', data.apikey)
        formData.append('timestamp', data.timestamp.toString())
        formData.append('signature', data.signature)
        formData.append('eager', data.eager)
        formData.append('folder', data.folder);

        const response = await fetch(url, {
          method: 'POST',
          body: formData
        })
        console.log('success', await response.json())
        alert('Upload was successful')
      } else {
        alert('No files')
      }
    } catch (error) {
      console.log('Failed to upload', error)
    }
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <input
            type="file"
            accept='.png, .jpg, .jpeg'
            onChange={handleUpload}
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home;

export async function getServerSideProps() {
  const baseUrl = 'http://localhost:3002/api'
  const res = await fetch(`${baseUrl}/sign`)
  const data = await res.json()

  console.log('data', data)
  return {
    props: {
      data
    }
  }
}
